version: "3.9"
services:
  app:
    container_name: my_project_APP
    build: ./
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: bitnami/postgresql
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres